#!/bin/bash

function upd {
cd /tmp
wget https://raw.githubusercontent.com/Entframe/FESK/master/firewall && chmod +x firewall
upstream_version=$(/tmp/firewall status)
installed_version=$(/etc/fesk/firewall status)
compare=$(/etc/fesk/utils/version_compare $installed_version $upstream_version)
if [ "$compare" == "<" ]; then
echo "Updating"
git clone https://github.com/Entframe/FESK.git && cd FESK
echo " "
echo "Enter your password to update: "
echo " "
sudo ./install.sh --update
else
echo "You have latest version installed"
fi
}

function helpfunction {
echo " "
echo "SYNTAX: "
echo "-S or --status : To display FESK firewall status"
echo "-U or --update : To update your installed FESK"
echo " "
}

case "$1" in
  "-S"|"--status") /etc/fesk/firewall status ;;
  "-U"|"--update") upd ;;
  "-H"|"--help"|*) helpfunction ;;
esac
